/**
 * Insights Markdown Generator
 *
 * Produces GitHub-flavored markdown from an ArchitectureReport.
 * Mirrors the structure of src/report.ts but tailored for insight data.
 */

import type { ArchitectureReport, Recommendation } from './types.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function escapeMd(str: string): string {
  return str.replace(/[`|]/g, '\\$&');
}

function mdTable(headers: string[], rows: string[][]): string {
  const header = `| ${headers.join(' | ')} |`;
  const divider = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => `| ${row.join(' | ')} |`).join('\n');
  return [header, divider, body].join('\n');
}

function priorityBadge(priority: Recommendation['priority']): string {
  const badges: Record<Recommendation['priority'], string> = {
    high: '🔴 High',
    medium: '🟡 Medium',
    low: '🔵 Low',
  };
  return badges[priority];
}

// ─── Generator ────────────────────────────────────────────────────────────────

/**
 * Generates a GitHub-flavored Markdown string from an ArchitectureReport.
 */
export function generateInsightsMarkdown(report: ArchitectureReport): string {
  const lines: string[] = [];
  const { summary, frontend, backend, database, infrastructure, monorepo } = report;
  const date = report.metadata.generatedAt.split('T')[0] ?? report.metadata.generatedAt;

  // ── Title ──────────────────────────────────────────────────────────────────
  lines.push(`# Architecture Report: ${escapeMd(summary.repoName)}`);
  lines.push('');
  lines.push(
    `> Generated by **Norix ${escapeMd(report.metadata.norixVersion)}** · ${date} · Modern Engine`,
  );
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Project Summary ────────────────────────────────────────────────────────
  lines.push('## Project Summary');
  lines.push('');
  lines.push(
    mdTable(
      ['Property', 'Value'],
      [
        ['Archetype', escapeMd(summary.archetype)],
        ['Language', escapeMd(summary.primaryLanguage)],
        ['Package Manager', escapeMd(summary.packageManager)],
        ['Repository', escapeMd(summary.repoName)],
        ['Type', summary.isMonorepo ? 'Monorepo' : 'Single Package'],
        ['Capabilities Detected', String(summary.detectedCapabilityCount)],
      ],
    ),
  );
  lines.push('');

  // ── Frontend ───────────────────────────────────────────────────────────────
  const hasFrontend =
    frontend.metaFramework !== undefined ||
    frontend.uiLibrary !== undefined ||
    frontend.bundler !== undefined;

  if (hasFrontend || frontend.hasTypeScript) {
    lines.push('---');
    lines.push('');
    lines.push('## Frontend');
    lines.push('');
    const rows: string[][] = [];
    if (frontend.metaFramework !== undefined) {
      rows.push(['Meta-framework', escapeMd(frontend.metaFramework)]);
    }
    if (frontend.uiLibrary !== undefined) {
      rows.push(['UI Library', escapeMd(frontend.uiLibrary)]);
    }
    if (frontend.bundler !== undefined) {
      rows.push(['Bundler', escapeMd(frontend.bundler)]);
    }
    if (frontend.styling.length > 0) {
      rows.push(['Styling', frontend.styling.map(escapeMd).join(', ')]);
    }
    rows.push(['TypeScript', frontend.hasTypeScript ? '✅ Yes' : '❌ No']);
    lines.push(mdTable(['Property', 'Value'], rows));
    lines.push('');
  }

  // ── Backend ────────────────────────────────────────────────────────────────
  const hasBackend =
    backend.frameworks.length > 0 ||
    backend.apiLayer.length > 0 ||
    backend.authentication.length > 0 ||
    backend.validation.length > 0;

  if (hasBackend) {
    lines.push('---');
    lines.push('');
    lines.push('## Backend');
    lines.push('');
    const rows: string[][] = [];
    if (backend.frameworks.length > 0) {
      rows.push(['Framework', backend.frameworks.map(escapeMd).join(', ')]);
    }
    if (backend.apiLayer.length > 0) {
      rows.push(['API Layer', backend.apiLayer.map(escapeMd).join(', ')]);
    }
    if (backend.authentication.length > 0) {
      rows.push(['Authentication', backend.authentication.map(escapeMd).join(', ')]);
    }
    if (backend.validation.length > 0) {
      rows.push(['Validation', backend.validation.map(escapeMd).join(', ')]);
    }
    if (backend.cache.length > 0) {
      rows.push(['Cache', backend.cache.map(escapeMd).join(', ')]);
    }
    if (backend.queue.length > 0) {
      rows.push(['Queue', backend.queue.map(escapeMd).join(', ')]);
    }
    lines.push(mdTable(['Property', 'Value'], rows));
    lines.push('');
  }

  // ── Database ───────────────────────────────────────────────────────────────
  const hasDb =
    database.drivers.length > 0 || database.orms.length > 0 || database.managedServices.length > 0;

  if (hasDb) {
    lines.push('---');
    lines.push('');
    lines.push('## Database');
    lines.push('');
    const rows: string[][] = [];
    if (database.drivers.length > 0) {
      rows.push(['Drivers', database.drivers.map(escapeMd).join(', ')]);
    }
    if (database.orms.length > 0) {
      rows.push(['ORM / Query Builder', database.orms.map(escapeMd).join(', ')]);
    }
    if (database.managedServices.length > 0) {
      rows.push(['Managed Services', database.managedServices.map(escapeMd).join(', ')]);
    }
    const dbType =
      [database.isRelational && 'Relational', database.isDocument && 'Document']
        .filter(Boolean)
        .join(' + ') || '—';
    rows.push(['Type', dbType]);
    lines.push(mdTable(['Property', 'Value'], rows));
    lines.push('');
  }

  // ── Infrastructure ─────────────────────────────────────────────────────────
  const hasInfra =
    infrastructure.ciCd.length > 0 ||
    infrastructure.deployment.length > 0 ||
    infrastructure.containerization.length > 0 ||
    infrastructure.monitoring.length > 0;

  if (hasInfra) {
    lines.push('---');
    lines.push('');
    lines.push('## Infrastructure');
    lines.push('');
    const rows: string[][] = [];
    if (infrastructure.ciCd.length > 0) {
      rows.push(['CI/CD', infrastructure.ciCd.map(escapeMd).join(', ')]);
    }
    if (infrastructure.deployment.length > 0) {
      rows.push(['Deployment', infrastructure.deployment.map(escapeMd).join(', ')]);
    }
    if (infrastructure.containerization.length > 0) {
      rows.push(['Containers', infrastructure.containerization.map(escapeMd).join(', ')]);
    }
    if (infrastructure.monitoring.length > 0) {
      rows.push(['Monitoring', infrastructure.monitoring.map(escapeMd).join(', ')]);
    }
    lines.push(mdTable(['Property', 'Value'], rows));
    lines.push('');
  }

  // ── Monorepo ───────────────────────────────────────────────────────────────
  if (monorepo !== undefined) {
    lines.push('---');
    lines.push('');
    lines.push('## Monorepo');
    lines.push('');
    lines.push(
      mdTable(
        ['Property', 'Value'],
        [
          ['Build Tool', escapeMd(monorepo.tool)],
          ['Workspace Count', String(monorepo.workspaceCount)],
        ],
      ),
    );
    if (monorepo.workspaceNames.length > 0) {
      lines.push('');
      lines.push('**Workspaces:**');
      for (const ws of monorepo.workspaceNames) {
        lines.push(`- \`${escapeMd(ws)}\``);
      }
    }
    lines.push('');
  }

  // ── Strengths ──────────────────────────────────────────────────────────────
  if (report.strengths.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## ✦ Strengths');
    lines.push('');
    for (const s of report.strengths) {
      lines.push(`- **${escapeMd(s.title)}** — ${escapeMd(s.detail)}`);
    }
    lines.push('');
  }

  // ── Risks ──────────────────────────────────────────────────────────────────
  if (report.risks.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## ⚠ Risks');
    lines.push('');
    for (const r of report.risks) {
      lines.push(`- **${escapeMd(r.title)}** — ${escapeMd(r.detail)}`);
    }
    lines.push('');
  }

  // ── Recommendations ────────────────────────────────────────────────────────
  if (report.recommendations.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## ◆ Recommendations');
    lines.push('');
    lines.push(
      mdTable(
        ['Priority', 'Recommendation', 'Detail'],
        report.recommendations.map((rec) => [
          priorityBadge(rec.priority),
          escapeMd(rec.title),
          escapeMd(rec.detail),
        ]),
      ),
    );
    lines.push('');
  }

  // ── Footer ─────────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push(
    `*Generated by [Norix](https://github.com/sreeragpariyarath/norix) — Repository Analysis CLI · ${date}*`,
  );

  return lines.join('\n');
}
