import { DetectorFactory } from './DetectorFactory.js';
import { NextJsDetector } from '../detectors/NextJsDetector.js';
import { ReactDetector } from '../detectors/ReactDetector.js';
import { ViteDetector } from '../detectors/ViteDetector.js';
import { ExpressDetector } from '../detectors/ExpressDetector.js';
import { FastifyDetector } from '../detectors/FastifyDetector.js';
import { NestJsDetector } from '../detectors/NestJsDetector.js';
import { PostgresDetector } from '../detectors/PostgresDetector.js';
import { MySqlDetector } from '../detectors/MySqlDetector.js';
import { MariaDbDetector } from '../detectors/MariaDbDetector.js';
import { SqliteDetector } from '../detectors/SqliteDetector.js';
import { MongoDbDetector } from '../detectors/MongoDbDetector.js';
import { RedisDetector } from '../detectors/RedisDetector.js';
import { PrismaDetector } from '../detectors/PrismaDetector.js';
import { DrizzleDetector } from '../detectors/DrizzleDetector.js';
import { TypeOrmDetector } from '../detectors/TypeOrmDetector.js';
import { SequelizeDetector } from '../detectors/SequelizeDetector.js';
import { MongooseDetector } from '../detectors/MongooseDetector.js';
import { DockerDetector } from '../detectors/DockerDetector.js';
import { DockerComposeDetector } from '../detectors/DockerComposeDetector.js';
import { KubernetesDetector } from '../detectors/KubernetesDetector.js';
import { HelmDetector } from '../detectors/HelmDetector.js';
import { TurboRepoDetector } from '../detectors/TurboRepoDetector.js';
import { NxDetector } from '../detectors/NxDetector.js';
import { LernaDetector } from '../detectors/LernaDetector.js';
import { NpmDetector } from '../detectors/NpmDetector.js';
import { PnpmDetector } from '../detectors/PnpmDetector.js';
import { YarnDetector } from '../detectors/YarnDetector.js';
import { BunDetector } from '../detectors/BunDetector.js';
import { GitHubActionsDetector } from '../detectors/GitHubActionsDetector.js';
import { GitLabCIDetector } from '../detectors/GitLabCIDetector.js';
import { CircleCIDetector } from '../detectors/CircleCIDetector.js';
import { AzurePipelinesDetector } from '../detectors/AzurePipelinesDetector.js';
import { VercelDetector } from '../detectors/VercelDetector.js';
import { NetlifyDetector } from '../detectors/NetlifyDetector.js';
import { RailwayDetector } from '../detectors/RailwayDetector.js';
import { RenderDetector } from '../detectors/RenderDetector.js';
import { CloudflareWorkersDetector } from '../detectors/CloudflareWorkersDetector.js';
import { VitestDetector } from '../detectors/VitestDetector.js';
import { JestDetector } from '../detectors/JestDetector.js';
import { PlaywrightDetector } from '../detectors/PlaywrightDetector.js';
import { CypressDetector } from '../detectors/CypressDetector.js';
import { MochaDetector } from '../detectors/MochaDetector.js';

/**
 * Creates and returns a pre-registered DetectorFactory containing all capability detectors.
 */
export function createDefaultFactory(): DetectorFactory {
  const factory = new DetectorFactory();
  factory.register('nextjs', NextJsDetector);
  factory.register('react', ReactDetector);
  factory.register('vite', ViteDetector);
  factory.register('express', ExpressDetector);
  factory.register('fastify', FastifyDetector);
  factory.register('nestjs', NestJsDetector);
  factory.register('postgres', PostgresDetector);
  factory.register('mysql', MySqlDetector);
  factory.register('mariadb', MariaDbDetector);
  factory.register('sqlite', SqliteDetector);
  factory.register('mongodb', MongoDbDetector);
  factory.register('redis', RedisDetector);
  factory.register('prisma', PrismaDetector);
  factory.register('drizzle', DrizzleDetector);
  factory.register('typeorm', TypeOrmDetector);
  factory.register('sequelize', SequelizeDetector);
  factory.register('mongoose', MongooseDetector);
  factory.register('docker', DockerDetector);
  factory.register('docker-compose', DockerComposeDetector);
  factory.register('kubernetes', KubernetesDetector);
  factory.register('helm', HelmDetector);
  factory.register('turborepo', TurboRepoDetector);
  factory.register('nx', NxDetector);
  factory.register('lerna', LernaDetector);
  factory.register('npm', NpmDetector);
  factory.register('pnpm', PnpmDetector);
  factory.register('yarn', YarnDetector);
  factory.register('bun', BunDetector);
  factory.register('github-actions', GitHubActionsDetector);
  factory.register('gitlab-ci', GitLabCIDetector);
  factory.register('circle-ci', CircleCIDetector);
  factory.register('azure-pipelines', AzurePipelinesDetector);
  factory.register('vercel', VercelDetector);
  factory.register('netlify', NetlifyDetector);
  factory.register('railway', RailwayDetector);
  factory.register('render', RenderDetector);
  factory.register('cloudflare-workers', CloudflareWorkersDetector);
  factory.register('vitest', VitestDetector);
  factory.register('jest', JestDetector);
  factory.register('playwright', PlaywrightDetector);
  factory.register('cypress', CypressDetector);
  factory.register('mocha', MochaDetector);
  return factory;
}
