/**
 * Report Generator
 *
 * Produces two report formats from AnalysisResult + DoctorResult:
 *  - Markdown (.md): human-readable, suitable for onboarding docs
 *  - JSON (.json): machine-readable, versioned schema
 *
 * Both are written to the output directory specified in ReportOptions.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import type {
  AnalysisResult,
  CapabilityCategory,
  DoctorFinding,
  DoctorResult,
  GeneratedReport,
  ReportOptions,
} from './types.js';
import { CATEGORY_LABELS, CATEGORY_ORDER } from './types.js';

// ─── Markdown Generation ──────────────────────────────────────────────────────

function mdTable(headers: string[], rows: string[][]): string {
  const header = `| ${headers.join(' | ')} |`;
  const divider = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((row) => `| ${row.join(' | ')} |`).join('\n');
  return [header, divider, body].join('\n');
}

function escapeMd(str: string): string {
  return str.replace(/[`|]/g, '\\$&');
}

function severityBadge(severity: 'warning' | 'info'): string {
  return severity === 'warning' ? '⚠ Warning' : 'ℹ Info';
}

function generateMarkdown(analysis: AnalysisResult, doctor: DoctorResult | null): string {
  const lines: string[] = [];
  const date = new Date().toISOString().split('T')[0];

  // ── Title ──────────────────────────────────────────────────────────────────
  lines.push(`# Repository Report: ${escapeMd(analysis.repoName)}`);
  lines.push('');
  lines.push(`> Generated by **Norix v1.0.0** · ${date}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ── Overview ───────────────────────────────────────────────────────────────
  lines.push('## Overview');
  lines.push('');

  const overviewRows: string[][] = [
    ['Name', escapeMd(analysis.repoName)],
    ['Language', analysis.language],
    ['Package Manager', analysis.packageManager],
    ['Type', analysis.isMonorepo ? `Monorepo (${analysis.workspaceNames.length} workspaces)` : 'Single Package'],
    ['Packages scanned', `${analysis.packageJsonCount} package.json file${analysis.packageJsonCount !== 1 ? 's' : ''}`],
  ];

  lines.push(mdTable(['Property', 'Value'], overviewRows));
  lines.push('');

  // ── Workspaces ─────────────────────────────────────────────────────────────
  if (analysis.isMonorepo && analysis.workspaceNames.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Workspaces');
    lines.push('');
    for (const ws of analysis.workspaceNames) {
      lines.push(`- \`${escapeMd(ws)}\``);
    }
    lines.push('');
  }

  // ── Capabilities ───────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push('## Capabilities');
  lines.push('');

  const detectedCats = CATEGORY_ORDER.filter(
    (cat) => (analysis.capabilities[cat]?.length ?? 0) > 0,
  );

  if (detectedCats.length === 0) {
    lines.push('*No known capabilities detected.*');
  } else {
    const capRows: string[][] = detectedCats.map((cat) => {
      const label = CATEGORY_LABELS[cat as CapabilityCategory] ?? cat;
      const matches = analysis.capabilities[cat as CapabilityCategory] ?? [];
      const detected = matches.map((m) => escapeMd(m.label)).join(', ');
      const flag = matches.length > 1 ? ' ⚠' : '';
      return [label, `${detected}${flag}`];
    });
    lines.push(mdTable(['Category', 'Detected'], capRows));
    lines.push('');
    if (detectedCats.some((c) => (analysis.capabilities[c as CapabilityCategory]?.length ?? 0) > 1)) {
      lines.push('> ⚠ Categories marked with ⚠ have multiple libraries detected — see Health Findings below.');
      lines.push('');
    }
  }

  // ── Health Findings ────────────────────────────────────────────────────────
  if (doctor && doctor.findings.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Health Findings');
    lines.push('');
    lines.push(
      `*${doctor.summary.total} finding${doctor.summary.total !== 1 ? 's' : ''} · ` +
      `${doctor.summary.warning} warning${doctor.summary.warning !== 1 ? 's' : ''} · ` +
      `${doctor.summary.info} info · These are observations, not errors.*`,
    );
    lines.push('');

    for (const finding of doctor.findings) {
      const badge = severityBadge(finding.severity);
      lines.push(`### ${badge}: ${escapeMd(finding.title)}`);
      lines.push('');

      const evidenceList = finding.evidence
        .map((e) => `\`${escapeMd(e.package)}\``)
        .join(', ');
      lines.push(`**Packages detected:** ${evidenceList}`);
      lines.push('');
      lines.push(finding.reasoning);
      lines.push('');
    }
  } else if (doctor) {
    lines.push('---');
    lines.push('');
    lines.push('## Health Findings');
    lines.push('');
    lines.push('✅ No capability overlaps detected.');
    lines.push('');
  }

  // ── Footer ─────────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push('');
  lines.push(
    '*Generated by [Norix](https://github.com/sreerag/norix) — Repository Intelligence CLI*',
  );

  return lines.join('\n');
}

// ─── JSON Generation ──────────────────────────────────────────────────────────

function generateJson(analysis: AnalysisResult, doctor: DoctorResult | null): unknown {
  return {
    $schema: 'https://norix.dev/schemas/report/v1.json',
    version: '1',
    norixVersion: '0.5.0',
    timestamp: new Date().toISOString(),
    repository: {
      name: analysis.repoName,
      root: analysis.repoRoot,
      isMonorepo: analysis.isMonorepo,
      workspaces: analysis.workspaceNames,
      language: analysis.language,
      packageManager: analysis.packageManager,
    },
    capabilities: analysis.capabilities,
    doctor: doctor
      ? {
          findings: doctor.findings,
          summary: doctor.summary,
        }
      : null,
    meta: {
      packageJsonCount: analysis.packageJsonCount,
      analyzeDurationMs: Math.round(analysis.duration),
      doctorDurationMs: doctor ? Math.round(doctor.duration) : null,
    },
  };
}

// ─── File Writer ──────────────────────────────────────────────────────────────

export function writeReports(
  options: ReportOptions,
  analysis: AnalysisResult,
  doctor: DoctorResult | null,
): GeneratedReport {
  const outputDir = resolve(options.outputDir);

  // Ensure output directory exists
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  const report: GeneratedReport = {};
  const doctorData = options.includeDoctor ? doctor : null;

  if (options.format === 'markdown' || options.format === 'all') {
    const content = generateMarkdown(analysis, doctorData);
    const path = join(outputDir, 'norix-report.md');
    writeFileSync(path, content, 'utf-8');
    report.markdownPath = path;
  }

  if (options.format === 'json' || options.format === 'all') {
    const content = JSON.stringify(generateJson(analysis, doctorData), null, 2);
    const path = join(outputDir, 'norix-report.json');
    writeFileSync(path, content, 'utf-8');
    report.jsonPath = path;
  }

  return report;
}
